project_id = "xvlpynxmtbihkarcgoyb"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.smoobu-sync]
    verify_jwt = false
  [functions.smoobu-webhook]
    verify_jwt = false
